export const ADD_PERSON_TO_FAVORITE = 'ADD_PERSON_TO_FAVORITE';
export const REMOVE_PERSON_FROM_FAVORITE = 'REMOVE_PERSON_FROM_FAVORITE';


export const CHANGE_TO_DARK = 'CHANGE_TO_DARK'
export const CHANGE_TO_LIGHT = 'CHANGE_TO_LIGHT'
export const CHANGE_TO_DEFAULT = 'CHANGE_TO_DEFAULT'